services:

  # =====================
  # USER
  # =====================

  User.Repository:
    class: src/Contexts/Core/User/infrastructure/persistence/TypeOrmUserRepository
    arguments: ["@Shared.ORM.Connection"]

  User.FindByCriteria.FinderByCriteria:
    class: src/Contexts/Core/User/application/FindByCriteria/FinderByCriteria
    arguments: ['@User.Repository']

  User.FindByCriteria.FindUsersByCriteriaQueryHandler:
    class: src/Contexts/Core/User/application/FindByCriteria/FindUsersByCriteriaQueryHandler
    arguments: ['@User.FindByCriteria.FinderByCriteria']
    tags:
      - { name: "queryHandler" }

  User.FindById.FinderById:
    class: src/Contexts/Core/User/application/FindById/FinderById
    arguments: ['@User.Repository']

  User.FindById.FindUserByIdQueryHandler:
    class: src/Contexts/Core/User/application/FindById/FindUserByIdQueryHandler
    arguments: ['@User.FindById.FinderById']
    tags:
      - { name: "queryHandler" }

  User.FindByEmail.FinderByEmail:
    class: src/Contexts/Core/User/application/FindByEmail/FinderByEmail
    arguments: ['@User.Repository']

  User.FindByEmail.FindUserByEmailQueryHandler:
    class: src/Contexts/Core/User/application/FindByEmail/FindUserByEmailQueryHandler
    arguments: ['@User.FindByEmail.FinderByEmail']
    tags:
      - { name: "queryHandler" }

  User.Create.Creator:
    class: src/Contexts/Core/User/application/Create/Creator
    arguments: ['@User.Repository']

  User.Create.CreateUserCommandHandler:
    class: src/Contexts/Core/User/application/Create/CreateUserCommandHandler
    arguments: ["@User.Create.Creator"]
    tags:
      - { name: "commandHandler" }

  User.Update.Updater:
    class: src/Contexts/Core/User/application/Update/Updater
    arguments: ['@User.Repository']

  User.Update.UpdateUserCommandHandler:
    class: src/Contexts/Core/User/application/Update/UpdaterUserCommandHandler
    arguments: ["@User.Update.Updater"]
    tags:
      - { name: "commandHandler" }

  User.UpdateIsAdmin.UpdaterIsAdmin:
    class: src/Contexts/Core/User/application/UpdateIsAdmin/UpdaterIsAdmin
    arguments: ['@User.Repository']

  User.UpdateIsAdmin.UpdateIsAdminUserCommandHandler:
    class: src/Contexts/Core/User/application/UpdateIsAdmin/UpdateIsAdminUserCommandHandler
    arguments: ["@User.UpdateIsAdmin.UpdaterIsAdmin"]
    tags:
      - { name: "commandHandler" }

  User.UpdatePassword.UpdatePassword:
    class: src/Contexts/Core/User/application/UpdatePassword/UpdatePassword
    arguments: ["@User.Repository"]

  User.UpdatePassword.UpdatePasswordUserCommandHandler:
    class: src/Contexts/Core/User/application/UpdatePassword/UpdatePasswordUserCommandHandler
    arguments: ["@User.UpdatePassword.UpdatePassword"]
    tags:
      - { name: "commandHandler" }

  User.Delete.Deleter:
    class: src/Contexts/Core/User/application/Delete/Deleter
    arguments: ['@User.Repository']

  User.Delete.DeleteUserCommandHandler:
    class: src/Contexts/Core/User/application/Delete/DeleteUserCommandHandler
    arguments: ["@User.Delete.Deleter"]
    tags:
      - { name: "commandHandler" }

  # =====================
  # ACCOUNT
  # =====================

  Account.Repository:
    class: src/Contexts/Core/Account/infrastructure/persistence/TypeOrmAccountRepository
    arguments: ["@Shared.ORM.Connection"]

  Account.Create.Creator:
    class: src/Contexts/Core/Account/application/Create/Creator
    arguments: ['@Account.Repository']

  Account.Create.CreateAccountCommandHandler:
    class: src/Contexts/Core/Account/application/Create/CreateAccountCommandHandler
    arguments: ["@Account.Create.Creator"]
    tags:
      - { name: "commandHandler" }

  Account.FindByCriteria.FinderByCriteria:
    class: src/Contexts/Core/Account/application/FindByCriteria/FinderByCriteria
    arguments: ['@Account.Repository']

  Account.FindByCriteria.FindAccountsByCriteriaQueryHandler:
    class: src/Contexts/Core/Account/application/FindByCriteria/FindAccountsByCriteriaQueryHandler
    arguments: ['@Account.FindByCriteria.FinderByCriteria']
    tags:
      - { name: "queryHandler" }

  Account.FindById.FinderById:
    class: src/Contexts/Core/Account/application/FindById/FinderById
    arguments: ['@Account.Repository']

  Account.FindById.FindAccountByIdQueryHandler:
    class: src/Contexts/Core/Account/application/FindById/FindAccountByIdQueryHandler
    arguments: ['@Account.FindById.FinderById']
    tags:
      - { name: "queryHandler" }

  Account.FindById.FindAccountsByUserIdQueryHandler:
    class: src/Contexts/Core/Account/application/FindById/FindAccountsByUserIdQueryHandler
    arguments: ['@Account.FindByCriteria.FinderByCriteria']
    tags:
      - { name: "queryHandler" }

  Account.Update.Updater:
    class: src/Contexts/Core/Account/application/Update/Updater
    arguments: ['@Account.Repository']

  Account.Update.UpdateAccountCommandHandler:
    class: src/Contexts/Core/Account/application/Update/UpdateAccountCommandHandler
    arguments: ["@Account.Update.Updater"]
    tags:
      - { name: "commandHandler" }

  Account.UpdateBalance.Updater:
    class: src/Contexts/Core/Account/application/UpdateBalance/Updater
    arguments: ['@Account.Repository']

  Account.Update.UpdateAccountBalanceCommandHandler:
    class: src/Contexts/Core/Account/application/UpdateBalance/UpdateAccountBalanceCommandHandler
    arguments: ["@Account.UpdateBalance.Updater"]
    tags:
      - { name: "commandHandler" }

  Account.Delete.Deleter:
    class: src/Contexts/Core/Account/application/Delete/Deleter
    arguments: ['@Account.Repository']

  Account.Delete.DeleteAccountCommandHandler:
    class: src/Contexts/Core/Account/application/Delete/DeleteAccountCommandHandler
    arguments: ["@Account.Delete.Deleter"]
    tags:
      - { name: "commandHandler" }

  # =====================
  # CARD
  # =====================

  Card.Repository:
    class: src/Contexts/Core/Card/infrastructure/persistence/TypeOrmCardRepository
    arguments: ["@Shared.ORM.Connection"]

  Card.Create.Creator:
    class: src/Contexts/Core/Card/application/Create/Creator
    arguments: ['@Card.Repository', '@Account.Repository']

  Card.Create.CreateCardCommandHandler:
    class: src/Contexts/Core/Card/application/Create/CreateCardCommandHandler
    arguments: ["@Card.Create.Creator"]
    tags:
      - { name: "commandHandler" }

  Card.FindByCriteria.FinderByCriteria:
    class: src/Contexts/Core/Card/application/FindByCriteria/FinderByCriteria
    arguments: ['@Card.Repository']

  Card.FindByCriteria.FindCardsByCriteriaQueryHandler:
    class: src/Contexts/Core/Card/application/FindByCriteria/FindCardsByCriteriaQueryHandler
    arguments: ['@Card.FindByCriteria.FinderByCriteria']
    tags:
      - { name: "queryHandler" }

  Card.FindById.FinderById:
    class: src/Contexts/Core/Card/application/FindById/FinderById
    arguments: ['@Card.Repository']

  Card.FindById.FindCardByIdQueryHandler:
    class: src/Contexts/Core/Card/application/FindById/FindCardByIdQueryHandler
    arguments: ['@Card.FindById.FinderById']
    tags:
      - { name: "queryHandler" }

  Card.FindByUserId.FinderByUserId:
    class: src/Contexts/Core/Card/application/FindByUserId/FinderByUserId
    arguments: ['@Card.Repository', '@Account.Repository']

  Card.FindByUserId.FindCardsByUserIdQueryHandler:
    class: src/Contexts/Core/Card/application/FindByUserId/FindCardsByUserIdQueryHandler
    arguments: ['@Card.FindByUserId.FinderByUserId']
    tags:
      - { name: "queryHandler" }

  Card.Update.Updater:
    class: src/Contexts/Core/Card/application/Update/Updater
    arguments: ['@Card.Repository']

  Card.Update.UpdateCardCommandHandler:
    class: src/Contexts/Core/Card/application/Update/UpdateCardCommandHandler
    arguments: ["@Card.Update.Updater"]
    tags:
      - { name: "commandHandler" }

  Card.UpdateLimit.UpdateCardLimit:
    class: src/Contexts/Core/Card/application/UpdateLimit/UpdateCardLimit
    arguments: ['@Card.Repository']

  Card.UpdateLimit.UpdateCardLimitCommandHandler:
    class: src/Contexts/Core/Card/application/UpdateLimit/UpdateCardLimitCommandHandler
    arguments: ["@Card.UpdateLimit.UpdateCardLimit"]
    tags:
      - { name: "commandHandler" }

  Card.Delete.Deleter:
    class: src/Contexts/Core/Card/application/Delete/Deleter
    arguments: ['@Card.Repository']

  Card.Delete.DeleteCardCommandHandler:
    class: src/Contexts/Core/Card/application/Delete/DeleteCardCommandHandler
    arguments: ["@Card.Delete.Deleter"]
    tags:
      - { name: "commandHandler" }

  Card.UpdateAccountCardBalance.Updater:
    class: src/Contexts/Core/Card/application/UpdateAccountCardBalance/Updater
    arguments: ['@Card.Repository']

  Card.UpdateAccountCardBalance.UpdateAccountCardBalanceCommandHandler:
    class: src/Contexts/Core/Card/application/UpdateAccountCardBalance/UpdateAccountCardBalanceCommandHandler
    arguments: ["@Card.UpdateAccountCardBalance.Updater"]
    tags:
      - { name: "commandHandler" }

  Card.UpdateAccountCardPin.Updater:
    class: src/Contexts/Core/Card/application/UpdateAccountCardPin/Updater
    arguments: ['@Card.Repository']

  Card.UpdateAccountCardPin.UpdateCardPinCommandHandler:
    class: src/Contexts/Core/Card/application/UpdateAccountCardPin/UpdateCardPinCommandHandler
    arguments: ["@Card.UpdateAccountCardPin.Updater"]
    tags:
      - { name: "commandHandler" }

  # =====================
  # Bank Operation
  # =====================

  BankOperation.Process.OperationStrategyRegistryFactory:
    class: src/Contexts/Core/BankOperation/application/Process/registry/OperationStrategyRegistryFactory

  BankOperation.Process.OperationStrategyRegistry:
    factory:
      class: src/Contexts/Core/BankOperation/application/Process/registry/OperationStrategyRegistryFactory
      method: "create"
    arguments:
      - '@Shared.CommandBus'
      - '@Shared.QueryBus'

  BankOperation.Process.ProcessBankOperationCreator:
    class: src/Contexts/Core/BankOperation/application/Process/ProcessBankOperationCreator
    arguments: ['@BankOperation.Process.OperationStrategyRegistry']

  BankOperation.Process.ProcessBankOperationCommandHandler:
    class: src/Contexts/Core/BankOperation/application/Process/ProcessBankOperationCommandHandler
    arguments: ["@BankOperation.Process.ProcessBankOperationCreator"]

  AccountMovement.Repository:
    class: src/Contexts/Core/AccountMovement/infrastructure/persistence/TypeOrmAccountMovementRepository
    arguments: ["@Shared.ORM.Connection"]

  AccountMovement.Create.Creator:
    class: src/Contexts/Core/AccountMovement/application/Create/Creator
    arguments: ['@AccountMovement.Repository']
  
  AccountMovement.Create.AccountMovementCommandHandler:
    class: src/Contexts/Core/AccountMovement/application/Create/AccountMovementCommandHandler
    arguments: ["@AccountMovement.Create.Creator"]
    tags:
      - { name: "commandHandler" }

  CardMovement.Repository:
    class: src/Contexts/Core/CardMovement/infrastructure/persistence/TypeOrmCardMovementRepository
    arguments: ["@Shared.ORM.Connection"]

  CreateCardMovement.Create.Creator:
    class: src/Contexts/Core/CardMovement/application/Create/Creator
    arguments: ['@CardMovement.Repository']

  CreateCardMovement.Create.CardMovementCommandHandler:
    class: src/Contexts/Core/CardMovement/application/Create/CreateCardMovementCommandHandler
    arguments: ["@CreateCardMovement.Create.Creator"]
    tags:
      - { name: "commandHandler" }