services:
  Apps.Core.Middleware.AuthMiddleware:
    class: src/apps/Core/middleware/AuthMiddleware
    arguments: ["@Shared.TokenDecoder"]

  Apps.Core.Middleware.IsAdminMiddleware:
    class: src/apps/Core/middleware/IsAdminMiddleware
    arguments: ["@Shared.QueryBus", "@Shared.TokenDecoder"]

  # USER

  Apps.Core.Controllers.RegisterPostController:
    class: src/apps/Core/controllers/http/User/RegisterPostController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.LoginPostController:
    class: src/apps/Core/controllers/http/User/LoginPostController
    arguments: ["@User.Repository"]

  Apps.Core.Controllers.UserDeleteController:
    class: src/apps/Core/controllers/http/User/UserDeleteController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.UserPutController:
    class: src/apps/Core/controllers/http/User/UserPutController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.UserPasswordPatchController:
    class: src/apps/Core/controllers/http/User/UserPasswordPatchController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.UserIsAdminPatchController:
    class: src/apps/Core/controllers/http/User/UserIsAdminPatchController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.MyselfGetController:
    class: src/apps/Core/controllers/http/User/MyselfGetController
    arguments: ["@Shared.QueryBus", "@Shared.TokenDecoder"]

  Apps.Core.Controllers.MyselfPutController:
    class: src/apps/Core/controllers/http/User/MyselfPutController
    arguments: ["@Shared.CommandBus", "@Shared.TokenDecoder"]

  Apps.Core.Controllers.UsersGetController:
    class: src/apps/Core/controllers/http/User/UsersGetController
    arguments: ["@Shared.QueryBus"]

  Apps.Core.Controllers.UserGetController:
    class: src/apps/Core/controllers/http/User/UserGetController
    arguments: ["@Shared.QueryBus"]

  Apps.Core.Controllers.UsernameGetController:
    class: src/apps/Core/controllers/http/User/UsernameGetController
    arguments: ["@Shared.QueryBus", "@Shared.TokenDecoder"]

  # ACCOUNT

  Apps.Core.Controllers.AccountGetController:
    class: src/apps/Core/controllers/http/Account/AccountGetController
    arguments: ["@Shared.QueryBus"]

  Apps.Core.Controllers.FindMyAccountsController:
    class: src/apps/Core/controllers/http/Account/FindMyAccountsController
    arguments: ["@Shared.QueryBus", "@Shared.TokenDecoder"]

  Apps.Core.Controllers.AccountsGetController:
    class: src/apps/Core/controllers/http/Account/AccountsGetController
    arguments: ["@Shared.QueryBus"]

  Apps.Core.Controllers.AccountDeleteController:
    class: src/apps/Core/controllers/http/Account/AccountDeleteController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.AccountPostController:
    class: src/apps/Core/controllers/http/Account/AccountPostController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.AccountPutController:
    class: src/apps/Core/controllers/http/Account/AccountPutController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.AccountPatchController:
    class: src/apps/Core/controllers/http/Account/AccountPatchController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.SocketHealthController:
    class: src/apps/Core/controllers/socket/HealthController
    arguments: []

  Apps.Core.Controllers.MyAccountGetController:
    class: src/apps/Core/controllers/http/Account/MyAccountGetController
    arguments: ["@Shared.QueryBus", "@Shared.TokenDecoder"]

  # CARD

  Apps.Core.Controllers.CardGetController:
    class: src/apps/Core/controllers/http/Card/CardGetController
    arguments: ["@Shared.QueryBus"]

  Apps.Core.Controllers.CardsGetController:
    class: src/apps/Core/controllers/http/Card/CardsGetController
    arguments: ["@Shared.QueryBus"]

  Apps.Core.Controllers.FindByIdCardController:
    class: src/apps/Core/controllers/http/Card/FindByIdCardController
    arguments: ["@Shared.QueryBus", "@Shared.TokenDecoder"]

  Apps.Core.Controllers.CardDeleteController:
    class: src/apps/Core/controllers/http/Card/CardDeleteController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.CardPostController:
    class: src/apps/Core/controllers/http/Card/CardPostController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.CardPutController:
    class: src/apps/Core/controllers/http/Card/CardPutController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.LimitCardPutController:
    class: src/apps/Core/controllers/http/Card/LimitCardPutController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.MyCardGetController:
    class: src/apps/Core/controllers/http/Card/MyCardGetController
    arguments: ["@Shared.QueryBus", "@Shared.TokenDecoder"]

  Apps.Core.Controllers.CardPinPutController:
    class: src/apps/Core/controllers/http/Card/CardPinPutController
    arguments: ["@Shared.CommandBus"]

  Apps.Core.Controllers.CardIsBlockedPutController:
    class: src/apps/Core/controllers/http/Card/CardIsBlockedPutController
    arguments: ["@Shared.CommandBus", "@Shared.QueryBus"]

  # BANK OPERATION

  Apps.Core.Controllers.BankOperationPostController:
    class: src/apps/Core/controllers/http/BankOperation/BankOperationPostController
    arguments: ["@Shared.CommandBus"]